apiVersion: apps/v1
kind: Deployment
metadata:
  name: kazre-springboot-app
  labels:
    app: kazre-springboot-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kazre-springboot-app
  template:
    metadata:
      labels:
        app: kazre-springboot-app
    spec:
      containers:
      - name: kazre-springboot-app
        image: gcr.io/sandbox-io-289003/kazre-app:master.40
        ports:
        - containerPort: 8080
        env:
        - name: YOUR_NAME
          valueFrom:
            configMapKeyRef:
              name: kazre-config
              key: YOUR_NAME
        
