pipeline {

  environment {
    PROJECT = "sandbox-io-289003"
    APP_NAME = "newest"
    FE_SVC_NAME = "${APP_NAME}-frontend"
    CLUSTER = "jenkins-cd"
    CLUSTER_ZONE = "us-east1-d"
    IMAGE_TAG = "gcr.io/${PROJECT}/${APP_NAME}:${env.BRANCH_NAME}.${env.BUILD_NUMBER}"
    JENKINS_CRED = "${PROJECT}"
  }

  agent {
    kubernetes {
      label 'my-agent'
      defaultContainer 'jnlp'
      yaml """
      apiVersion: v1
      kind: Pod
      metadata:
        labels:
          app: my-agent
      spec:
        serviceAccountName: cd-jenkins
        containers:
        - name: nodejs
          image: node:latest
          command:
          - cat
          tty: true
        - name: python
          image: python:latest
          command:
          - cat
          tty: true
        - name: mysql
          image: mysql:latest
          command:
          - cat
          tty: true
      """
    }
  }

  stages {

    stage('Run MySQL') {
      steps {
        container('mysql') {
          sh 'mysql --version' // print MySQL version
          sh 'mysql -u <username> -p<password> -h <host> -e "SHOW DATABASES <database_name>;"' // execute a SQL query
        }
      }
    }

    stage('Run Python') {
      steps {
        container('python') {
          sh 'python --version' // print Python version
          sh 'pip install -r requirements.txt' // install dependencies
          sh 'python main.py' // run the main script
        }
      }
    }

    stage('Run Node.js') {
      steps {
        container('nodejs') {
          sh 'node --version' // print Node.js version
          sh 'npm install' // install dependencies
          sh 'npm run build' // build the project
        }
      }
    }

  }
}
