pipeline {
  environment {
    PROJECT = "sandbox-io-289003"
    APP_NAME = "newest"
    FE_SVC_NAME = "${APP_NAME}-frontend"
    CLUSTER = "jenkins-cd"
    CLUSTER_ZONE = "us-east1-d"
    IMAGE_TAG = "gcr.io/${PROJECT}/${APP_NAME}:${env.BRANCH_NAME}.${env.BUILD_NUMBER}"
    JENKINS_CRED = "${PROJECT}"
  }

  agent {
    kubernetes {
      label 'my-agent'
      defaultContainer 'jnlp'
      yaml """
      apiVersion: v1
      kind: Pod
      metadata:
        labels:
          app: my-agent
      spec:
        serviceAccountName: cd-jenkins
        containers:
        - name: nodejs
          image: node:latest
          command:
          - cat
          tty: true
        - name: python
          image: python:latest
          command:
          - cat
          tty: true
        - name: mysql
          image: mysql:latest
          command:
          - cat
          tty: true
        - name: docker
          image: docker:latest
          command:
          - cat
          tty: true
      """
    }
  }

  stages {

    stage('Run MySQL') {
      steps {
        container('mysql') {
          sh 'mysql --version' // print MySQL version
        }
      }
    }

    stage('Run Python') {
      steps {
        container('python') {
          sh 'pip list'
        }
      }
    }

    stage('Run Node.js') {
      steps {
        container('nodejs') {
          sh 'pwd'
        }
      }
    }

    stage('List bucket contents') {
      steps {
        container('python') {
          withCredentials([gcpServiceAccount(credentialsId: 'jenkins-sa', jsonKeyVariable: 'GCP_SA_KEY')]) {
            sh """
              google/cloud-sdk:slim
              gsutil ls gs://${PROJECT}-bucket
            """
          }
        }
      }
    }
  }
}
