apiVersion: v1
kind: Service
metadata:
  name: kazre-load_balencer-service
  labels:
    app: kazre-springboot-app
spec:
  type: LoadBalancer
  selector:
    app: kazre-springboot-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080